export * from "./model.js";
export { parseRefUnit, type Dim, type RefUnit } from "./units.js";
export { parseFormula, formulaVariables, FormulaError, type Expr } from "./expression.js";
export { computeChantier, computeWorkItem, requiredInputs, type RequiredInputs, type MissingData, type Origin, type WorkItemInput, type WorkItemResult, type NeedResult, type Question, type TraceLine, type Assumption, type ParamValue, type SlotChoice, type EngineOptions, type CompanyPreferences } from "./engine.js";
export { identifyProducts, type Identification } from "./resolve.js";
export { checkReferential } from "./integrity.js";
export { ROOFING_REFERENTIAL } from "./data/roofing.js";
export { paramsFromContext, type ChantierContext, type SiteFact, type ContextConflict } from "./context.js";
export { purchaseList, type PurchaseRow } from "./purchase-list.js";
export { planQuote, factsFromReading, readSiteNotes, type QuoteLine, type QuotePlan, type LinePlan } from "./plan.js";
export { scoreQuote, type QuoteScore, type LineOutcome, type Answer } from "./scorecard.js";
export { documentationNeeds, type DocumentationNeed } from "./documentation.js";
export { mergeReferentials, type ReferentialLayer, type ReferentialProvider } from "./layers.js";
export { applyLineRoles, proposeLineRoles, type LineRole, type RoleLine, type RoleProposal } from "./line-roles.js";
export { climateZone, departmentOf, isCoastal, postalCodeIn } from "./zone.js";
