export * from "./model.js";
export { parseRefUnit, type Dim, type RefUnit } from "./units.js";
export { parseFormula, formulaVariables, FormulaError, type Expr } from "./expression.js";
export { computeChantier, computeWorkItem, requiredInputs, type RequiredInputs, type MissingData, type Origin, type WorkItemInput, type WorkItemResult, type NeedResult, type RuleToConfirm, type Question, type TraceLine, type Assumption, type ParamValue, type SlotChoice, type EngineOptions, type CompanyPreferences } from "./engine.js";
export { identifyProducts, type Identification } from "./resolve.js";
export { checkReferential } from "./integrity.js";
export { referentialSchema, validateReferential, loadReferential, ReferentialFileError } from "./schema.js";
export { ROOFING_REFERENTIAL } from "./data/roofing.js";
export { PLATRERIE_REFERENTIAL } from "./data/platrerie.js";
export { CARRELAGE_REFERENTIAL } from "./data/carrelage.js";
export { PEINTURE_REFERENTIAL } from "./data/peinture.js";
export { MACONNERIE_REFERENTIAL } from "./data/maconnerie.js";
export { ELECTRICITE_REFERENTIAL } from "./data/electricite.js";
export { PLOMBERIE_REFERENTIAL } from "./data/plomberie.js";
export { MENUISERIE_REFERENTIAL } from "./data/menuiserie.js";
export { CHAUFFAGE_VENTILATION_REFERENTIAL } from "./data/chauffage-ventilation.js";
export { REFERENTIALS, METIER_NAMES, referentialFor, tradeIdOf } from "./registry.js";
export { paramsFromContext, type ChantierContext, type SiteFact, type ContextConflict } from "./context.js";
export { purchaseList, type PurchaseRow } from "./purchase-list.js";
export { planQuote, factsFromReading, readSiteNotes, readExclusions, exclusionFor, type SiteExclusion, type QuoteLine, type QuotePlan, type LinePlan } from "./plan.js";
export { scoreQuote, type QuoteScore, type LineOutcome, type Answer } from "./scorecard.js";
export { documentationNeeds, type DocumentationNeed } from "./documentation.js";
export { mergeReferentials, type ReferentialLayer, type ReferentialProvider } from "./layers.js";
export { applyLineRoles, proposeLineRoles, type LineRole, type RoleLine, type RoleProposal } from "./line-roles.js";
export { climateZone, departmentOf, isCoastal, postalCodeIn } from "./zone.js";
